# Generated by Django 5.0.2 on 2024-02-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_DB',
            fields=[
                ('sno', models.IntegerField(primary_key='sno', serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('publisher', models.CharField(max_length=60)),
            ],
        ),
    ]
